services:
  - type: web
    name: fastapi-todo
    runtime: python
    pythonVersion: "3.11"
    buildCommand: "pip install --no-cache-dir --only-binary :all: -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
